### ISSUE TITLE
OSError: [Errno 22] Invalid argument when running inference on Windows 11

### ISSUE THREAD

**Issue by eormal** [kepengxu/PGTFormer#10]
描述：在 Windows 11 系统上运行 inference.py 时遇到 OSError: [Errno 22] Invalid argument 错误。
Description: OSError: [Errno 22] Invalid argument error encountered when running inference.py on Windows 11 system.

以下是详细的错误信息和环境配置：
The following is the detailed error information and environment configuration:

重现步骤 :
Reproduction steps:

在 Windows 11 上安装所有依赖项并设置环境，使用项目自带的测试数据（视频）。
Install all dependencies and set up the environment on Windows 11, using the test data provided by the project (video).

运行以下命令：
Run the following command:
`python inference.py --input_video=assets/inputdemovideo.mp4 --output_video=exp/output_demo.mp4
`
错误日志如下：
The error log is as follows:
```
C:\ProgramData\anaconda3\envs\PGTFormer\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
C:\ProgramData\anaconda3\envs\PGTFormer\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Working with z of shape (1, 256, 32, 32) = 262144 dimensions.
Traceback (most recent call last):
  File "inference.py", line 156, in <module>
    process_video_ffmpeg(args.input_video, args.output_video, model)
  File "inference.py", line 65, in process_video_ffmpeg
    pipe_out.stdin.write(processed_frame.tobytes())
OSError: [Errno 22] Invalid argument
```

环境信息 ：
Environment information:
Python 3.8.19
PyTorch 2.1.0+cu118

**Comment by kepengxu** [comment]
I guess it's because of the lack of exp folder

**Comment by amani153** [comment]
(py3.8) PS E:\Studio\PGTFormer-main> python inference_cn.py --input_video=assets/inputdemovideo.mp4 --output_video=exp/output_demo.mp4
C:\Users\PC\.conda\envs\py3.8\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
C:\Users\PC\.conda\envs\py3.8\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Working with z of shape (1, 256, 32, 32) = 262144 dimensions.

After the program runs, there is no other information output, and the graphics memory is constantly occupied, but the GPU and CPU usage rates are 0% ？

Environment information:
win11 + py3.8 + cuda11.8 + torch 2.0.1

**Comment by eormal** [comment]
https://github.com/user-attachments/assets/c40af689-3e55-412c-afac-be26f477f32d

感谢解答！
不过，遇到了新的问题，执行命令后GPU负载短暂上升一小段时间后回复到正常，exp文件夹里发现有output_demo.mp4，但是大小只有44字节，并且之后一直卡在“Working with z of shape (1, 256, 32, 32) = 262144 dimensions.”这一步
Thanks for the answer!
However, I encountered a new problem. After executing the command, the GPU load increased briefly for a short time and then returned to normal. I found output_demo.mp4 in the exp folder, but the size was only 44 bytes, and it was stuck at the step "Working with z of shape (1, 256, 32, 32) = 262144 dimensions."

**Comment by eormal** [comment]
> I guess it's because of the lack of exp folder

Please take a look at my latest question, thanks

**Comment by kepengxu** [comment]
你好
我刚刚注意到这个问题，可以按步调试一下执行代码吗，我想知道卡在了哪一步

**Comment by kepengxu** [comment]
有任何问题可以联系我微信
neuralnetwork99

这个github没有提醒

**Comment by kackbob** [comment]
may be you try use cv2 read frame,then write result

**Comment by ak01user** [comment]
> 2024-08-30.17-16-02.mp4 
> 感谢解答！ 不过，遇到了新的问题，执行命令后GPU负载短暂上升一小段时间后回复到正常，exp文件夹里发现有output_demo.mp4，但是大小只有44字节，并且之后一直卡在“Working with z of shape (1, 256, 32, 32) = 262144 dimensions.”这一步 Thanks for the answer! However, I encountered a new problem. After executing the command, the GPU load increased briefly for a short time and then returned to normal. I found output_demo.mp4 in the exp folder, but the size was only 44 bytes, and it was stuck at the step "Working with z of shape (1, 256, 32, 32) = 262144 dimensions."

#7

**Comment by KFK121** [comment]
> 2024-08-30.17-16-02.mp4 
> 感谢解答！ 不过，遇到了新的问题，执行命令后GPU负载短暂上升一小段时间后回复到正常，exp文件夹里发现有output_demo.mp4，但是大小只有44字节，并且之后一直卡在“Working with z of shape (1, 256, 32, 32) = 262144 dimensions.”这一步 Thanks for the answer! 谢谢你的回答！ However, I encountered a new problem. After executing the command, the GPU load increased briefly for a short time and then returned to normal. I found output_demo.mp4 in the exp folder, but the size was only 44 bytes, and it was stuck at the step "Working with z of shape (1, 256, 32, 32) = 262144 dimensions."但是，我遇到了一个新问题。执行命令后，GPU 负载短暂增加，然后恢复正常。我在 exp 文件夹中找到了 output_demo.mp4，但大小只有 44 字节，并且卡在“Working with z of shape （1， 256， 32， 32） = 262144 dimensions”步骤。

The same issue, has it been resolved?
