### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe 

### ISSUE THREAD

**Issue by DerryChan** [kepengxu/PGTFormer#9]
python inference.py --input_video=assets/inputdemovideo.mp4 --output_video=exp/output_demo.mp4       

                                    
/root/miniconda3/envs/pgtformer/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.                 
  warnings.warn(                                                                                
/root/miniconda3/envs/pgtformer/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)                            
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]                          
Working with z of shape (1, 256, 32, 32) = 262144 dimensions.                                   
Traceback (most recent call last):                                                              
  File "inference.py", line 156, in <module>                                                    
    process_video_ffmpeg(args.input_video, args.output_video, model)                            
  File "inference.py", line 65, in process_video_ffmpeg                                         
    pipe_out.stdin.write(processed_frame.tobytes())                                             
BrokenPipeError: [Errno 32] Broken pipe

**Comment by kepengxu** [comment]
may be not have exp folder?
you can show me full log(*^_^*)

**Comment by kackbob** [comment]
first,you create exp folder in project,then run it

**Comment by huangxin168** [comment]
same error!
have mkdir exp
